version: 2
updates:
# Fetch and update latest `npm` packages
- package-ecosystem: npm
  directory: '/'
  schedule:
    interval: monthly
    time: '00:00'
  open-pull-requests-limit: 3
  reviewers:
    - condini-mastheus
  assignees:
    - condini-mastheus
  commit-message:
    prefix: fix
    prefix-development: chore
    include: scope
